# Generated by Django 5.0.4 on 2024-04-09 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.PositiveSmallIntegerField(default=0)),
                ('cpt', models.PositiveSmallIntegerField(default=0)),
                ('trestbps', models.PositiveSmallIntegerField()),
                ('chol', models.PositiveSmallIntegerField()),
                ('fbs', models.PositiveSmallIntegerField()),
                ('restecg', models.PositiveSmallIntegerField()),
                ('thalach', models.PositiveSmallIntegerField()),
                ('exang', models.PositiveSmallIntegerField(default=0)),
                ('oldpeak', models.DecimalField(decimal_places=2, max_digits=3)),
                ('slope', models.PositiveSmallIntegerField()),
                ('ca', models.PositiveSmallIntegerField()),
                ('thal', models.PositiveSmallIntegerField()),
                ('result', models.PositiveSmallIntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
