# Generated by Django 5.0.4 on 2024-04-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_data_age_alter_data_ca_alter_data_chol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='age',
        ),
        migrations.RemoveField(
            model_name='data',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='data',
            name='chol',
        ),
        migrations.RemoveField(
            model_name='data',
            name='cpt',
        ),
        migrations.RemoveField(
            model_name='data',
            name='exang',
        ),
        migrations.RemoveField(
            model_name='data',
            name='fbs',
        ),
        migrations.RemoveField(
            model_name='data',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='data',
            name='oldpeak',
        ),
        migrations.RemoveField(
            model_name='data',
            name='restecg',
        ),
        migrations.RemoveField(
            model_name='data',
            name='result',
        ),
        migrations.RemoveField(
            model_name='data',
            name='slope',
        ),
        migrations.RemoveField(
            model_name='data',
            name='thal',
        ),
        migrations.RemoveField(
            model_name='data',
            name='thalach',
        ),
        migrations.RemoveField(
            model_name='data',
            name='trestbps',
        ),
    ]
